spring.application.name=aiinbox

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url = jdbc:h2:mem:socialcrmtestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# This ensures Hibernate creates the tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update

meta.api.pat = EAAs6n11Yp9EBRPFIjmIsPi6JhNQARDh1fLQLTdhcrbfuJHgVZBIg5iktQLxnApvjn30SeIYwh3r0UYROzggAKlS7JZArmJdt1ZC8mt0KvR2RG3u0eWdp0WXq3KLp9ULG2ZBzxVRZC6dCheBzqhpMlenhVsp8AK702e485MFZCoF1TsIZBsNiBLZBh5dmwDgk1OCS30X2tKWV0ri9apatBAHvbwZDZD

meta.api.base_url =  https://graph.facebook.com/

spring.ai.google.genai.api-key=AQ.Ab8RN6KYpIY4PgV2CDHDXaIlJRtso5pfTDVGVOOVLfvzlX0HIg
# Change the model to the stable 1.5 version
# Updated for April 2026 stable requirements
spring.ai.google.genai.chat.options.model=gemini-2.5-flash